"""empty message

Revision ID: 64018388e7a5
Revises: 7096cb2526a7
Create Date: 2021-11-11 15:08:48.799642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64018388e7a5'
down_revision = '7096cb2526a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
